behaviors:
  PrisonerBehaviour:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size:  40960
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.997
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 512
    summary_freq: 10000